version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mern_assignment
  mongo:
    image: mongo
    ports:
      - '27017:27017'
